import type { M19Liveness, M19RecoveryPlan, M19RecoveryRuntime } from './m19Recovery';
import styles from './LiveRouteWorkspace.module.css';

export type M19RecoveryView = 'plans' | 'network' | 'nodes' | 'readiness' | 'incidents' | 'inference';
const short = (value: string | null) => value === null ? 'none' : value.startsWith('sha256:') ? `${value.slice(0, 15)}…` : value;

export function M19RecoveryPanel({ liveness, plan, runtime, view }: { readonly liveness: M19Liveness; readonly plan: M19RecoveryPlan; readonly runtime: M19RecoveryRuntime; readonly view: M19RecoveryView }) {
  const requests = runtime.requests.slice(-8);
  return <section className={styles.panel} aria-label={`${view} scoped recovery evidence`}>
    <div className={styles.panelTitlebar}><div><p className={styles.eyebrow}>Scoped recovery</p><h2>{view === 'plans' ? 'Deterministic recovery intent' : view === 'network' ? 'Surviving and successor tracks' : view === 'nodes' ? 'Traffic-aware peer liveness' : view === 'readiness' ? 'Recovery qualification gates' : view === 'incidents' ? 'Scoped failure and recovery history' : 'Monotonic request recovery'}</h2></div><span className={styles.evidenceBadge}>generation fenced</span></div>
    {view === 'plans' ? <><dl className={styles.measurements}><div><dt>Candidate state</dt><dd>{plan.candidate_state.replaceAll('_', ' ')}</dd></div><div><dt>Equivalent generations</dt><dd>{plan.equivalent_candidate_generations}</dd></div><div><dt>Retained tracks</dt><dd>{plan.surviving_track_ids.length}</dd></div><div><dt>Provisioning</dt><dd>{plan.provisioning_allowed ? 'allowed' : 'withheld'}</dd></div><div><dt>Circuit breaker</dt><dd>{runtime.breaker.state}{runtime.breaker.open_until_unix_ms ? ` until ${new Date(runtime.breaker.open_until_unix_ms).toISOString()}` : ''}</dd></div></dl><p>Incumbent tracks remain immutable. Join, drift, and departure create content-addressed candidates; emergency loss may bypass only hysteresis, never qualification.</p></> : null}
    {view === 'network' ? <div className={styles.tableWrap}><table><thead><tr><th>Track</th><th>Role</th><th>Decode / KV</th><th>Failure domain</th></tr></thead><tbody>{plan.surviving_track_ids.map((track) => <tr key={track}><th scope="row">{short(track)}</th><td>surviving incumbent</td><td>unchanged</td><td>retained</td></tr>)}{plan.successors.map((successor) => <tr key={successor.track_id}><th scope="row">{short(successor.track_id)}</th><td>qualified successor</td><td>{successor.decode_mode} · {successor.kv_compatibility}</td><td>{successor.failure_domain}</td></tr>)}</tbody></table></div> : null}
    {view === 'nodes' ? <div className={styles.tableWrap}><table><thead><tr><th>Subject</th><th>State</th><th>Misses / fresh</th><th>Last observation</th></tr></thead><tbody>{liveness.subjects.map((subject) => <tr key={subject.subject_id}><th scope="row">{subject.subject_id}</th><td>{subject.state}</td><td>{subject.consecutive_misses} / {subject.consecutive_fresh}</td><td>{new Date(subject.last_observed_unix_ms).toISOString()}</td></tr>)}</tbody></table></div> : null}
    {view === 'readiness' ? <><dl className={styles.measurements}><div><dt>Successors</dt><dd>{plan.successors.length}</dd></div><div><dt>Compatible KV</dt><dd>{plan.successors.filter((item) => item.kv_compatibility === 'compatible').length}</dd></div><div><dt>Max recoveries</dt><dd>{runtime.maximum_recovery_attempts}</dd></div><div><dt>Evidence</dt><dd>{short(liveness.evidence_digest)}</dd></div></dl><p>Replay is labelled <strong>full context replay</strong> and never claims KV transfer. KV continuity is shown only for a compatible, fenced successor.</p></> : null}
    {view === 'incidents' ? <>{liveness.incidents.length === 0 ? <p>No scoped liveness incident is retained.</p> : <ol>{liveness.incidents.map((incident) => <li key={incident.incident_id}><strong>{incident.scope} · {incident.reason.replaceAll('_', ' ')}</strong> — {incident.action.replaceAll('_', ' ')}; outcome {incident.terminal_outcome.replaceAll('_', ' ')}{incident.affected_track_ids.length ? `; tracks ${incident.affected_track_ids.map(short).join(', ')}` : ''}</li>)}</ol>}{requests.filter((request) => request.terminal_state === 'aborted').map((request) => <p role="alert" key={request.request_id}><strong>Truthful abort:</strong> {request.request_id} · {request.terminal_reason?.replaceAll('_', ' ')} · no continuity claimed.</p>)}</> : null}
    {view === 'inference' ? requests.length === 0 ? <p>No retained recovery attempt.</p> : <div className={styles.tableWrap}><table><thead><tr><th>Request</th><th>Attempt</th><th>Committed</th><th>Recovery</th><th>Successor</th><th>KV</th><th>Terminal</th></tr></thead><tbody>{requests.map((request) => <tr key={request.request_id}><th scope="row">{request.request_id}</th><td>{request.attempt}</td><td>{request.committed_token_count} tokens</td><td>{request.recovery_mode.replaceAll('_', ' ')}</td><td>{short(request.successor_track_id)}</td><td>{request.kv_outcome.replaceAll('_', ' ')}</td><td>{request.terminal_state ?? 'active'}{request.cleanup_complete ? ' · cleaned' : ''}</td></tr>)}</tbody></table></div> : null}
    <p><small>{plan.claim_boundary}</small></p>
  </section>;
}
