export const M20_PLAN_PATH = '/__mycelium/m20-speculative-plan';
export const M20_RUNTIME_PATH = '/__mycelium/m20-speculative-runtime';

export type M20ModelIdentity = Readonly<{ model_id: string; model_revision: string; tokenizer_digest: string; vocabulary_size: number; special_tokens_digest: string; position_semantics_digest: string; kv_schema_digest: string }>;
export type M20Measurements = Readonly<{ sample_count: number; target_only_tpot_ms: number | null; draft_tpot_ms: number | null; verification_batch_ms: number | null; proposal_transfer_ms: number | null; observed_acceptance_fraction: number | null; predicted_gain_fraction: number | null; observed_gain_fraction: number | null }>;
export type M20SpeculativePlan = Readonly<{ protocol: 'mycelium.m20_speculative_plan.v1'; binding: Readonly<Record<string, string | number>>; target: M20ModelIdentity; draft: M20ModelIdentity; workload_id: string; proposal_width: number; acceptance_distribution: readonly number[]; compatibility: Readonly<{ tokenizer: boolean; vocabulary: boolean; special_tokens: boolean; position_semantics: boolean; separate_kv_ownership: boolean; batched_target_verification: boolean }>; measurements: M20Measurements; decision: Readonly<{ state: 'disabled' | 'qualified_enabled'; reason: string; material_gain_threshold: number; target_fallback: true }>; privacy: string; plan_digest: string }>;
export type M20Request = Readonly<{ request_id: string; proposal_width: number; proposed_count: number; target_verified_count: number; accepted_count: number; rejected_count: number; rollback_count: number; fallback_state: 'none' | 'draft_lost' | 'policy_disabled' | 'verification_failed'; terminal_state: 'completed' | 'cancelled' | 'aborted'; cleanup_complete: true }>;
export type M20SpeculativeRuntime = Readonly<{ protocol: 'mycelium.m20_speculative_runtime.v1'; binding: Readonly<Record<string, string | number>>; mode: 'disabled' | 'speculative' | 'target_fallback'; requests: readonly M20Request[]; runtime_digest: string }>;

function record(value: unknown, fields: readonly string[], path: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new TypeError(`${path} must be an object`);
  const item = value as Record<string, unknown>;
  if (Object.keys(item).sort().join('|') !== [...fields].sort().join('|')) throw new TypeError(`${path} has unknown or missing fields`);
  return item;
}
function text(value: unknown, path: string): string { if (typeof value !== 'string' || value.length === 0 || value.length > 512) throw new TypeError(`${path} must be bounded text`); return value; }
function integer(value: unknown, path: string): number { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) throw new TypeError(`${path} must be a non-negative integer`); return value; }
function number(value: unknown, path: string): number { if (typeof value !== 'number' || !Number.isFinite(value) || value < 0) throw new TypeError(`${path} must be a non-negative number`); return value; }
function optionalNumber(value: unknown, path: string): number | null { return value === null ? null : number(value, path); }
function bool(value: unknown, path: string): boolean { if (typeof value !== 'boolean') throw new TypeError(`${path} must be boolean`); return value; }
function list(value: unknown, path: string): unknown[] { if (!Array.isArray(value) || value.length > 4096) throw new TypeError(`${path} must be a bounded array`); return value; }
function binding(value: unknown): Readonly<Record<string, string | number>> { const fields = ['deployment_id', 'deployment_epoch', 'graph_digest', 'membership_generation', 'model_id', 'model_revision', 'qualification_id', 'qualification_digest']; const item = record(value, fields, 'binding'); const result: Record<string, string | number> = {}; for (const field of fields) result[field] = typeof item[field] === 'number' ? integer(item[field], `binding.${field}`) : text(item[field], `binding.${field}`); return Object.freeze(result); }
function model(value: unknown, path: string): M20ModelIdentity { const item = record(value, ['model_id', 'model_revision', 'tokenizer_digest', 'vocabulary_size', 'special_tokens_digest', 'position_semantics_digest', 'kv_schema_digest'], path); return Object.freeze({ model_id: text(item.model_id, `${path}.model_id`), model_revision: text(item.model_revision, `${path}.model_revision`), tokenizer_digest: text(item.tokenizer_digest, `${path}.tokenizer_digest`), vocabulary_size: integer(item.vocabulary_size, `${path}.vocabulary_size`), special_tokens_digest: text(item.special_tokens_digest, `${path}.special_tokens_digest`), position_semantics_digest: text(item.position_semantics_digest, `${path}.position_semantics_digest`), kv_schema_digest: text(item.kv_schema_digest, `${path}.kv_schema_digest`) }); }

export function decodeM20SpeculativePlan(value: unknown): M20SpeculativePlan {
  const source = record(value, ['protocol', 'binding', 'target', 'draft', 'workload_id', 'proposal_width', 'acceptance_distribution', 'compatibility', 'measurements', 'decision', 'privacy', 'plan_digest'], 'm20_plan');
  if (source.protocol !== 'mycelium.m20_speculative_plan.v1') throw new TypeError('m20 plan protocol is invalid');
  const compatibility = record(source.compatibility, ['tokenizer', 'vocabulary', 'special_tokens', 'position_semantics', 'separate_kv_ownership', 'batched_target_verification'], 'compatibility');
  const measurements = record(source.measurements, ['sample_count', 'target_only_tpot_ms', 'draft_tpot_ms', 'verification_batch_ms', 'proposal_transfer_ms', 'observed_acceptance_fraction', 'predicted_gain_fraction', 'observed_gain_fraction'], 'measurements');
  const decision = record(source.decision, ['state', 'reason', 'material_gain_threshold', 'target_fallback'], 'decision');
  if (!['disabled', 'qualified_enabled'].includes(String(decision.state)) || decision.target_fallback !== true) throw new TypeError('m20 decision is invalid');
  const distribution = Object.freeze(list(source.acceptance_distribution, 'acceptance_distribution').map((item) => number(item, 'acceptance_distribution item')));
  return Object.freeze({ protocol: 'mycelium.m20_speculative_plan.v1', binding: binding(source.binding), target: model(source.target, 'target'), draft: model(source.draft, 'draft'), workload_id: text(source.workload_id, 'workload_id'), proposal_width: integer(source.proposal_width, 'proposal_width'), acceptance_distribution: distribution, compatibility: Object.freeze({ tokenizer: bool(compatibility.tokenizer, 'compatibility.tokenizer'), vocabulary: bool(compatibility.vocabulary, 'compatibility.vocabulary'), special_tokens: bool(compatibility.special_tokens, 'compatibility.special_tokens'), position_semantics: bool(compatibility.position_semantics, 'compatibility.position_semantics'), separate_kv_ownership: bool(compatibility.separate_kv_ownership, 'compatibility.separate_kv_ownership'), batched_target_verification: bool(compatibility.batched_target_verification, 'compatibility.batched_target_verification') }), measurements: Object.freeze({ sample_count: integer(measurements.sample_count, 'measurements.sample_count'), target_only_tpot_ms: optionalNumber(measurements.target_only_tpot_ms, 'measurements.target_only_tpot_ms'), draft_tpot_ms: optionalNumber(measurements.draft_tpot_ms, 'measurements.draft_tpot_ms'), verification_batch_ms: optionalNumber(measurements.verification_batch_ms, 'measurements.verification_batch_ms'), proposal_transfer_ms: optionalNumber(measurements.proposal_transfer_ms, 'measurements.proposal_transfer_ms'), observed_acceptance_fraction: optionalNumber(measurements.observed_acceptance_fraction, 'measurements.observed_acceptance_fraction'), predicted_gain_fraction: optionalNumber(measurements.predicted_gain_fraction, 'measurements.predicted_gain_fraction'), observed_gain_fraction: optionalNumber(measurements.observed_gain_fraction, 'measurements.observed_gain_fraction') }), decision: Object.freeze({ state: decision.state as 'disabled' | 'qualified_enabled', reason: text(decision.reason, 'decision.reason'), material_gain_threshold: number(decision.material_gain_threshold, 'decision.material_gain_threshold'), target_fallback: true }), privacy: text(source.privacy, 'privacy'), plan_digest: text(source.plan_digest, 'plan_digest') });
}

export function decodeM20SpeculativeRuntime(value: unknown): M20SpeculativeRuntime {
  const source = record(value, ['protocol', 'binding', 'mode', 'requests', 'runtime_digest'], 'm20_runtime');
  if (source.protocol !== 'mycelium.m20_speculative_runtime.v1' || !['disabled', 'speculative', 'target_fallback'].includes(String(source.mode))) throw new TypeError('m20 runtime authority is invalid');
  const requests = list(source.requests, 'requests').map((value, index): M20Request => { const item = record(value, ['request_id', 'proposal_width', 'proposed_count', 'target_verified_count', 'accepted_count', 'rejected_count', 'rollback_count', 'fallback_state', 'terminal_state', 'cleanup_complete'], `requests[${index}]`); if (!['none', 'draft_lost', 'policy_disabled', 'verification_failed'].includes(String(item.fallback_state)) || !['completed', 'cancelled', 'aborted'].includes(String(item.terminal_state)) || item.cleanup_complete !== true) throw new TypeError('m20 request state is invalid'); return Object.freeze({ request_id: text(item.request_id, 'request_id'), proposal_width: integer(item.proposal_width, 'proposal_width'), proposed_count: integer(item.proposed_count, 'proposed_count'), target_verified_count: integer(item.target_verified_count, 'target_verified_count'), accepted_count: integer(item.accepted_count, 'accepted_count'), rejected_count: integer(item.rejected_count, 'rejected_count'), rollback_count: integer(item.rollback_count, 'rollback_count'), fallback_state: item.fallback_state as M20Request['fallback_state'], terminal_state: item.terminal_state as M20Request['terminal_state'], cleanup_complete: true }); });
  return Object.freeze({ protocol: 'mycelium.m20_speculative_runtime.v1', binding: binding(source.binding), mode: source.mode as M20SpeculativeRuntime['mode'], requests: Object.freeze(requests), runtime_digest: text(source.runtime_digest, 'runtime_digest') });
}

export interface M20SpeculationClient { load(signal?: AbortSignal): Promise<readonly [M20SpeculativePlan, M20SpeculativeRuntime]> }
export class HttpM20SpeculationClient implements M20SpeculationClient {
  constructor(private readonly fetcher: typeof fetch = globalThis.fetch.bind(globalThis)) {}
  async load(signal?: AbortSignal): Promise<readonly [M20SpeculativePlan, M20SpeculativeRuntime]> {
    const request = (path: string) => this.fetcher(path, { method: 'GET', credentials: 'same-origin', cache: 'no-store', redirect: 'error', headers: { Accept: 'application/json' }, signal });
    const responses = await Promise.all([request(M20_PLAN_PATH), request(M20_RUNTIME_PATH)]);
    if (responses.some((response) => !response.ok)) throw new Error(`m20_speculation_${responses.map((response) => response.status).join('_')}`);
    const documents = await Promise.all(responses.map((response) => response.json()));
    return Object.freeze([decodeM20SpeculativePlan(documents[0]), decodeM20SpeculativeRuntime(documents[1])] as const);
  }
}
