const digest = `sha256:${'a'.repeat(64)}`;
const member = (id: string, peerClass: string, runtime: string, eligible: boolean, route: boolean, external = false) => ({ member_id: id, peer_class: peerClass, runtime_backend: runtime, trust_state: 'invited', generation: 2, incarnation: `${id}-inc`, freshness: 'fresh', revocation_state: 'active', activation_eligible: eligible, route_participant: route, eligibility_reason: eligible ? 'eligible' : 'activation_protocol_unavailable', connectivity: route ? 'direct' : 'unknown', external_network: external, endpoint_identity_digest: digest });
export const m21HeterogeneousFixture = {
  protocol: 'mycelium.m21_heterogeneous_swarm.v1', generated_at_unix_ms: 1_900_000_000_000,
  binding: { swarm_id: 'swarm', seed_key_digest: digest, seed_node_id: 'seed', deployment_id: 'deployment', model_id: 'Qwen/model', model_revision: 'revision', membership_generation: 2 },
  policy: { invitation_ownership: 'owner_only', operator_approval: 'required', maximum_invite_ttl_seconds: 600, single_use: true, request_quota_per_hour: 60, byte_quota_per_hour: 1073741824, audit_retention_days: 30, revocation_supported: true, credential_rotation_supported: true, abuse_response: 'revoke_then_rotate', permissionless_participation: false, byzantine_resistance: false, malicious_worker_confidentiality: false },
  members: [member('peer-mac', 'mac_mlx_iroh', 'mlx', true, true), member('peer-linux', 'linux_numpy_iroh', 'numpy', true, true, true), member('peer-browser', 'browser_http', 'browser', false, false)],
  paths: [{ source_member_id: 'peer-mac', destination_member_id: 'peer-linux', path_class: 'direct', relay_region: null, cold_rtt_ms: 20, warm_rtt_ms: 12, jitter_ms: 1, loss_ratio: 0, goodput_bytes_per_second: 30000, reconnect_count: 0, connection_generation: 1, selected_path_changes: 1, sample_count: 5 }],
  route: { physical: true, route_alive: true, heterogeneous: true, participant_count: 2, runtime_class_count: 2, frame_count_before: 10, frame_count_after: 20, latest_output_token_count: 3, tailscale_product_dependency: false, activation_transport: 'endpointid_authenticated_iroh', operator_staging_transport: 'ssh_or_tailscale_optional' },
  gate_state: 'qualified', exclusions: [], privacy: 'no credentials, prompts, output, tensors, activations, raw endpoint ids, private addresses, paths, or usernames', evidence_digest: digest,
} as const;
