import type { M21HeterogeneousEvidence } from './m21Heterogeneous';
import styles from './LiveRouteWorkspace.module.css';

export type M21HeterogeneousView = 'nodes' | 'network' | 'plans' | 'readiness' | 'settings' | 'lab';
const short = (value: string) => value.startsWith('sha256:') ? `${value.slice(0, 15)}…` : value;

export function M21HeterogeneousPanel({ evidence, view }: { readonly evidence: M21HeterogeneousEvidence; readonly view: M21HeterogeneousView }) {
  const routeMembers = evidence.members.filter((member) => member.route_participant);
  const ineligible = evidence.members.filter((member) => !member.activation_eligible);
  return <section className={styles.panel} aria-label={`M21 ${view} heterogeneous swarm evidence`}>
    <div className={styles.panelTitlebar}><div><p className={styles.eyebrow}>M21 · heterogeneous internet-native swarm</p><h2>{view === 'nodes' ? 'Signed runtime inventory' : view === 'network' ? 'EndpointID-authenticated paths' : view === 'readiness' ? 'Heterogeneous route qualification' : view === 'settings' ? 'External participation policy' : view === 'lab' ? 'Device-class admission boundary' : 'Cross-runtime deployment intent'}</h2></div><span className={styles.evidenceBadge}>{evidence.gate_state}</span></div>
    {view === 'nodes' || view === 'lab' ? <div className={styles.tableWrap}><table><thead><tr><th>Peer</th><th>Class / runtime</th><th>Freshness</th><th>Activation</th><th>Connectivity</th></tr></thead><tbody>{evidence.members.map((member) => <tr key={member.member_id}><th scope="row">{member.member_id}</th><td>{member.peer_class}<br/><small>{member.runtime_backend}</small></td><td>{member.freshness} · gen {member.generation}</td><td>{member.activation_eligible ? member.route_participant ? 'route participant' : 'eligible, idle' : `ineligible · ${member.eligibility_reason.replaceAll('_', ' ')}`}</td><td>{member.connectivity}{member.external_network ? ' · external network' : ''}</td></tr>)}</tbody></table></div> : null}
    {view === 'network' ? <><dl className={styles.measurements}><div><dt>Activation transport</dt><dd>{evidence.route.activation_transport.replaceAll('_', ' ')}</dd></div><div><dt>Tailscale product dependency</dt><dd>{evidence.route.tailscale_product_dependency ? 'yes' : 'no'}</dd></div><div><dt>Runtime classes</dt><dd>{evidence.route.runtime_class_count}</dd></div><div><dt>Path samples</dt><dd>{evidence.paths.reduce((total, path) => total + path.sample_count, 0)}</dd></div></dl><div className={styles.tableWrap}><table><thead><tr><th>Path</th><th>Class</th><th>Cold / warm RTT</th><th>Jitter / loss</th><th>Goodput</th></tr></thead><tbody>{evidence.paths.map((path) => <tr key={`${path.source_member_id}:${path.destination_member_id}`}><th scope="row">{path.source_member_id} → {path.destination_member_id}</th><td>{path.path_class}{path.relay_region ? ` · ${path.relay_region}` : ''}</td><td>{path.cold_rtt_ms.toFixed(1)} / {path.warm_rtt_ms.toFixed(1)} ms</td><td>{path.jitter_ms.toFixed(1)} ms / {(path.loss_ratio * 100).toFixed(2)}%</td><td>{(path.goodput_bytes_per_second / 1_000).toFixed(1)} kB/s</td></tr>)}</tbody></table></div></> : null}
    {view === 'plans' ? <><dl className={styles.measurements}><div><dt>Route participants</dt><dd>{routeMembers.length}</dd></div><div><dt>Runtime backends</dt><dd>{[...new Set(routeMembers.map((member) => member.runtime_backend))].join(' + ')}</dd></div><div><dt>Observed frames</dt><dd>{evidence.route.frame_count_before} → {evidence.route.frame_count_after}</dd></div><div><dt>External probes</dt><dd>{ineligible.length} safely excluded</dd></div></dl><p>Membership and activation are separate. The planner may place layers only on currently qualified runtime classes; browser and mobile probes remain visible without receiving model activations.</p></> : null}
    {view === 'readiness' ? <><dl className={styles.measurements}><div><dt>Gate</dt><dd>{evidence.gate_state}</dd></div><div><dt>Physical route</dt><dd>{evidence.route.physical && evidence.route.route_alive ? 'alive' : 'not proven'}</dd></div><div><dt>Heterogeneous</dt><dd>{evidence.route.heterogeneous ? `${evidence.route.runtime_class_count} runtime classes` : 'not proven'}</dd></div><div><dt>Output tokens</dt><dd>{evidence.route.latest_output_token_count}</dd></div><div><dt>Evidence</dt><dd>{short(evidence.evidence_digest)}</dd></div></dl><p>{evidence.exclusions.length === 0 ? 'All M21 gate requirements are evidenced.' : `Excluded: ${evidence.exclusions.join(', ')}`}</p></> : null}
    {view === 'settings' ? <><dl className={styles.measurements}><div><dt>Invitation</dt><dd>{String(evidence.policy.invitation_ownership).replaceAll('_', ' ')}</dd></div><div><dt>Approval</dt><dd>{String(evidence.policy.operator_approval)}</dd></div><div><dt>Invite TTL</dt><dd>{String(evidence.policy.maximum_invite_ttl_seconds)} s</dd></div><div><dt>Revocation</dt><dd>{evidence.policy.revocation_supported ? 'supported' : 'unavailable'}</dd></div><div><dt>Audit retention</dt><dd>{String(evidence.policy.audit_retention_days)} days</dd></div></dl><p>Participation is invite-only. Mycelium does not claim permissionless participation, Byzantine resistance, or confidentiality from an assigned malicious worker.</p></> : null}
    <p><small>{evidence.privacy}</small></p>
  </section>;
}
