import type { M22ReleaseEvidence } from './m22Release';
import styles from './LiveRouteWorkspace.module.css';

export type M22ReleaseView = 'inference' | 'lab' | 'network' | 'nodes' | 'plans' | 'readiness' | 'incidents' | 'settings';

export function M22ReleasePanel({ evidence, view }: { readonly evidence: M22ReleaseEvidence; readonly view: M22ReleaseView }) {
  return <section className={styles.panel} aria-label={`M22 release closure for ${view}`}>
    <p className={styles.eyebrow}>M22 · release closure</p>
    <h2>{evidence.gate_state === 'qualified' ? 'Release gate qualified' : 'Release gate withheld'}</h2>
    {view === 'inference' && <dl className={styles.measurements}><div><dt>Useful model</dt><dd>{evidence.model.model_id} · {evidence.model.parameter_class}</dd></div><div><dt>Physical completion</dt><dd>{evidence.physical.request_completed ? `${evidence.physical.output_token_count} output tokens` : 'Not proven'}</dd></div><div><dt>Local cache</dt><dd>{evidence.model.local_cache_reused && !evidence.model.network_download_performed ? 'Reused · no download' : 'Not proven'}</dd></div></dl>}
    {view === 'network' && <dl className={styles.measurements}><div><dt>Physical participants</dt><dd>{evidence.physical.participant_count}</dd></div><div><dt>Runtime classes</dt><dd>{evidence.physical.runtime_class_count}</dd></div><div><dt>Activation transport</dt><dd>{evidence.physical.activation_transport}</dd></div><div><dt>Tailscale product dependency</dt><dd>{evidence.physical.tailscale_product_dependency ? 'Yes' : 'No'}</dd></div></dl>}
    {view === 'plans' && <><dl className={styles.measurements}><div><dt>Qualified larger model</dt><dd>{evidence.model.model_id} · {evidence.model.reason}</dd></div><div><dt>Qwen3-8B adapter</dt><dd>{evidence.qwen3_8b.adapter_verified ? 'Verified' : 'Not verified'}</dd></div><div><dt>Qwen3-8B placement</dt><dd>{evidence.qwen3_8b.qualified ? 'Qualified' : `Blocked · ${evidence.qwen3_8b.reason}`}</dd></div></dl></>}
    {view === 'nodes' && <dl className={styles.measurements}><div><dt>Service packages</dt><dd>{evidence.services.package_count} · {evidence.services.roles.join(', ')}</dd></div><div><dt>Agent renewal</dt><dd>{evidence.services.continuous_renewal ? 'Jittered + bounded reconnect' : 'Not proven'}</dd></div><div><dt>Foreground route restart</dt><dd>{evidence.services.foreground_route_restart_verified ? 'Verified' : 'Not verified'}</dd></div><div><dt>Managed-service restart</dt><dd>{evidence.services.restart_verified && evidence.services.coordinator_restart_verified ? 'Node + coordinator verified' : 'Incomplete'}</dd></div><div><dt>Restart proof</dt><dd><code>{evidence.services.managed_restart_evidence_digest.slice(0, 18)}…</code></dd></div></dl>}
    {view === 'readiness' && <dl className={styles.measurements}><div><dt>UI audit</dt><dd>{evidence.ui_audit.verified_count}/{evidence.ui_audit.requirement_count}</dd></div><div><dt>Python / UI / Rust</dt><dd>{evidence.tests.python_passed} / {evidence.tests.ui_passed} / {evidence.tests.rust_passed}</dd></div><div><dt>Browsers</dt><dd>{evidence.tests.browser_engines.join(', ') || 'Not proven'}</dd></div><div><dt>Evidence digest</dt><dd>{evidence.evidence_digest}</dd></div></dl>}
    {view === 'incidents' && <><p>{evidence.reviewer.negative_case_verified ? 'Reviewer-node unavailable/ineligible negative case verified.' : 'Reviewer negative case remains unverified.'}</p>{evidence.exclusions.length ? <ul>{evidence.exclusions.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No release exclusions recorded.</p>}</>}
    {view === 'settings' && <dl className={styles.measurements}><div><dt>Service platforms</dt><dd>{evidence.services.platform_classes.join(', ')}</dd></div><div><dt>Graceful drain / log rotation</dt><dd>{evidence.services.graceful_drain && evidence.services.log_rotation ? 'Configured' : 'Incomplete'}</dd></div><div><dt>Clean bootstrap</dt><dd>{evidence.source.clean_bootstrap ? 'Verified' : 'Not verified'}</dd></div></dl>}
    {view === 'lab' && <dl className={styles.measurements}><div><dt>Reviewer bundle</dt><dd>{evidence.reviewer.bundle_version}</dd></div><div><dt>Idempotent preflight</dt><dd>{evidence.reviewer.preflight_idempotent ? 'Verified' : 'Not verified'}</dd></div><div><dt>Surrogate external stage</dt><dd>{evidence.reviewer.surrogate_verified && evidence.reviewer.assigned_stage ? 'Verified' : 'Not verified'}</dd></div></dl>}
  </section>;
}
