export type MembershipState = 'invited' | 'trusted' | 'reachable' | 'assigned' | 'qualified' | 'revoked';
export type MembershipConnectivity = 'direct' | 'relayed' | 'local' | 'disconnected' | 'stale' | 'unknown';
export interface MembershipMember { readonly member_id: string; readonly state: MembershipState; readonly connectivity: MembershipConnectivity; readonly endpoint_id: string | null; readonly evidence: 'supplied' | 'unknown'; }
export interface MembershipStatus { readonly protocol: 'mycelium.product_membership.v1'; readonly generated_at: string; readonly members: readonly MembershipMember[]; readonly unknowns: readonly string[]; }
export interface MembershipInvite { readonly invite_code: string; readonly expires_at: string; readonly single_use: true; }
export interface MembershipJoinResult { readonly accepted: boolean; readonly member_id: string; readonly state: MembershipState; }
export interface MembershipRevokeResult { readonly revoked: boolean; readonly member_id: string; }
export interface MembershipClient {
  status(): Promise<MembershipStatus>;
  createInvite(expiresInSeconds: number): Promise<MembershipInvite>;
  join(inviteCode: string, endpointId?: string): Promise<MembershipJoinResult>;
  revoke(memberId: string): Promise<MembershipRevokeResult>;
}
export class MembershipClientError extends Error { constructor(readonly code: string, message = code) { super(message); this.name = 'MembershipClientError'; } }
type Fetcher = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export interface MembershipClientOptions { readonly fetcher?: Fetcher; readonly statusPath?: string; readonly invitePath?: string; readonly joinPath?: string; readonly revokePath?: string; readonly maxResponseBytes?: number; }
const states = new Set<MembershipState>(['invited', 'trusted', 'reachable', 'assigned', 'qualified', 'revoked']);
const connectivity = new Set<MembershipConnectivity>(['direct', 'relayed', 'local', 'disconnected', 'stale', 'unknown']);
function sameOriginPath(path: string): string { if (!path.startsWith('/') || path.startsWith('//') || path.includes('://')) throw new MembershipClientError('unsafe_endpoint', 'membership endpoints must be same-origin paths'); return path; }
function record(value: unknown): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new MembershipClientError('invalid_product_contract'); return value as Record<string, unknown>; }
function text(value: unknown, field: string): string { if (typeof value !== 'string' || value.length === 0 || value.length > 512) throw new MembershipClientError('invalid_product_contract', field); return value; }
function exact(value: Record<string, unknown>, keys: readonly string[]): void { if (Object.keys(value).some((key) => !keys.includes(key))) throw new MembershipClientError('invalid_product_contract'); }
function member(value: unknown): MembershipMember { const item = record(value); exact(item, ['member_id', 'state', 'connectivity', 'endpoint_id', 'evidence']); const state = text(item.state, 'state') as MembershipState; const link = text(item.connectivity, 'connectivity') as MembershipConnectivity; if (!states.has(state) || !connectivity.has(link) || (item.endpoint_id !== null && typeof item.endpoint_id !== 'string') || !['supplied', 'unknown'].includes(String(item.evidence))) throw new MembershipClientError('invalid_product_contract'); return Object.freeze({ member_id: text(item.member_id, 'member_id'), state, connectivity: link, endpoint_id: item.endpoint_id as string | null, evidence: item.evidence as 'supplied' | 'unknown' }); }
export class HttpMembershipClient implements MembershipClient {
  private readonly fetcher: Fetcher; private readonly paths: Record<'status'|'invite'|'join'|'revoke', string>; private readonly max: number;
  constructor(options: MembershipClientOptions = {}) { this.fetcher = options.fetcher ?? fetch; this.paths = { status: sameOriginPath(options.statusPath ?? '/api/v1/membership/status'), invite: sameOriginPath(options.invitePath ?? '/api/v1/membership/invite'), join: sameOriginPath(options.joinPath ?? '/api/v1/membership/join'), revoke: sameOriginPath(options.revokePath ?? '/api/v1/membership/revoke') }; this.max = options.maxResponseBytes ?? 65_536; }
  private async request(path: string, init: RequestInit = {}): Promise<unknown> { const response = await this.fetcher(path, { ...init, credentials: 'same-origin', referrerPolicy: 'no-referrer', headers: { accept: 'application/json', ...(init.body === undefined ? {} : { 'content-type': 'application/json' }) }, redirect: 'error' }); const declared = Number(response.headers.get('content-length') ?? '0'); if (Number.isFinite(declared) && declared > this.max) throw new MembershipClientError('response_too_large'); const body = await response.text(); if (new TextEncoder().encode(body).byteLength > this.max) throw new MembershipClientError('response_too_large'); if (!response.ok) throw new MembershipClientError('membership_request_failed'); try { return JSON.parse(body); } catch { throw new MembershipClientError('invalid_product_contract'); } }
  async status(): Promise<MembershipStatus> { const value = record(await this.request(this.paths.status)); exact(value, ['protocol', 'generated_at', 'members', 'unknowns']); if (value.protocol !== 'mycelium.product_membership.v1' || !Array.isArray(value.members) || !Array.isArray(value.unknowns) || value.unknowns.some((item) => typeof item !== 'string')) throw new MembershipClientError('invalid_product_contract'); return Object.freeze({ protocol: value.protocol, generated_at: text(value.generated_at, 'generated_at'), members: Object.freeze(value.members.map(member)), unknowns: Object.freeze([...value.unknowns]) as readonly string[] }); }
  async createInvite(expiresInSeconds: number): Promise<MembershipInvite> { if (!Number.isInteger(expiresInSeconds) || expiresInSeconds < 30 || expiresInSeconds > 3600) throw new MembershipClientError('invalid_invite_expiry'); const value = record(await this.request(this.paths.invite, { method: 'POST', body: JSON.stringify({ expires_in_seconds: expiresInSeconds, single_use: true }) })); exact(value, ['invite_code', 'expires_at', 'single_use']); if (value.single_use !== true) throw new MembershipClientError('invalid_product_contract'); return Object.freeze({ invite_code: text(value.invite_code, 'invite_code'), expires_at: text(value.expires_at, 'expires_at'), single_use: true }); }
  async join(inviteCode: string, endpointId?: string): Promise<MembershipJoinResult> { const value = record(await this.request(this.paths.join, { method: 'POST', body: JSON.stringify({ invite_code: text(inviteCode, 'invite_code'), ...(endpointId === undefined ? {} : { endpoint_id: text(endpointId, 'endpoint_id') }) }) })); exact(value, ['accepted', 'member_id', 'state']); const state = text(value.state, 'state') as MembershipState; if (typeof value.accepted !== 'boolean' || !states.has(state)) throw new MembershipClientError('invalid_product_contract'); return Object.freeze({ accepted: value.accepted, member_id: text(value.member_id, 'member_id'), state }); }
  async revoke(memberId: string): Promise<MembershipRevokeResult> { const value = record(await this.request(this.paths.revoke, { method: 'POST', body: JSON.stringify({ member_id: text(memberId, 'member_id') }) })); exact(value, ['revoked', 'member_id']); if (typeof value.revoked !== 'boolean') throw new MembershipClientError('invalid_product_contract'); return Object.freeze({ revoked: value.revoked, member_id: text(value.member_id, 'member_id') }); }
}
