import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export interface ProductSettings { readonly theme: 'night' | 'system'; readonly density: 'comfortable' | 'compact'; readonly reducedMotion: boolean; readonly highContrast: boolean; readonly concealNetworkIdentity: boolean; }
export interface SettingsContextValue { readonly settings: ProductSettings; readonly update: (patch: Partial<ProductSettings>) => void; readonly reset: () => void; }
const defaults: ProductSettings = Object.freeze({ theme: 'night', density: 'comfortable', reducedMotion: false, highContrast: false, concealNetworkIdentity: true });
const storageKey = 'mycelium.product-ui.preferences.v1';
const SettingsContext = createContext<SettingsContextValue | null>(null);
function load(): ProductSettings { try { const value = JSON.parse(localStorage.getItem(storageKey) ?? 'null') as Partial<ProductSettings> | null; if (value === null) return defaults; return { theme: value.theme === 'system' ? 'system' : 'night', density: value.density === 'compact' ? 'compact' : 'comfortable', reducedMotion: value.reducedMotion === true, highContrast: value.highContrast === true, concealNetworkIdentity: value.concealNetworkIdentity !== false }; } catch { return defaults; } }
export function SettingsProvider({ children }: { readonly children: ReactNode }) { const [settings, setSettings] = useState<ProductSettings>(load); const update = (patch: Partial<ProductSettings>) => setSettings((current) => ({ ...current, ...patch })); const reset = () => setSettings(defaults); useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify(settings)); } catch { /* Preferences remain in memory when storage is unavailable. */ } document.documentElement.dataset.theme = settings.theme; document.documentElement.dataset.density = settings.density; document.documentElement.dataset.reducedMotion = String(settings.reducedMotion); document.documentElement.dataset.highContrast = String(settings.highContrast); }, [settings]); const value = useMemo(() => ({ settings, update, reset }), [settings]); return <SettingsContext.Provider value={value}>{children}</SettingsContext.Provider>; }
export function useProductSettings(): SettingsContextValue { const value = useContext(SettingsContext); if (value === null) throw new Error('useProductSettings requires SettingsProvider'); return value; }
