"""Authoritative executable contract registry used by generators and audit."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ContractSpec:
    fixture_name: str
    protocol: str
    owner_sources: tuple[str, ...]


CONTRACT_SPECS = (
    ContractSpec(
        "route-plan-v2.json",
        "mycelium.route_plan.v2",
        (
            "mycelium_layer_planner/contracts.py",
            "mycelium_layer_planner/serialization.py",
            "mycelium_layer_planner/validation.py",
        ),
    ),
    ContractSpec(
        "manual-provisioning-route-v1.json",
        "mycelium.manual_provisioning_route.v1",
        ("route_contract.py",),
    ),
    ContractSpec(
        "layer-assignment-v2.json",
        "mycelium.layer_assignment.v2",
        (
            "layer_assignment.py",
            "model_manifest.py",
            "model_adapters.py",
            "route_contract.py",
            "runtime_contracts.py",
        ),
    ),
    ContractSpec(
        "artifact-verification-report-v1.json",
        "mycelium.artifact_verification_report.v1",
        ("weight_provisioning.py", "layer_assignment.py"),
    ),
    ContractSpec(
        "provisioning-audit-v1.json",
        "mycelium.provisioning_audit.v1",
        ("weight_provisioning.py", "layer_assignment.py", "route_contract.py"),
    ),
    ContractSpec(
        "gossip-router-view-v1.json",
        "mycelium.gossip.router_view.v1",
        ("mycelium_gossip/views.py",),
    ),
    ContractSpec(
        "gossip-allocator-view-v1.json",
        "mycelium.gossip.allocator_view.v1",
        ("mycelium_gossip/views.py",),
    ),
    ContractSpec(
        "gossip-evidence-bundle-v1.json",
        "mycelium.gossip.evidence_bundle.v1",
        (
            "mycelium_gossip/evidence_bundle.py",
            "mycelium_gossip/service.py",
            "mycelium_gossip/views.py",
            "mycelium_gossip/registry.py",
            "mycelium_gossip/schema.py",
            "mycelium_gossip/state.py",
        ),
    ),
    ContractSpec(
        "signed-gossip-evidence-bundle-v1.json",
        "mycelium.gossip.signed_evidence_bundle.v1",
        (
            "mycelium_gossip/signed_bundle.py",
            "mycelium_gossip/evidence_bundle.py",
            "mycelium_capacity_profiles/document.py",
            "mycelium_qualification/signing.py",
        ),
    ),
    ContractSpec(
        "layer-planner-snapshot-v1.json",
        "mycelium.layer_planner_snapshot.v1",
        (
            "mycelium_layer_planner/gossip_adapter.py",
            "mycelium_layer_planner/planner.py",
            "mycelium_layer_planner/contracts.py",
        ),
    ),
    ContractSpec(
        "control-plane-tranche-v1.json",
        "mycelium.control_plane_tranche.v1",
        (
            "planner_assignment.py",
            "layer_assignment.py",
            "runtime_contracts.py",
            "mycelium_gossip/evidence_bundle.py",
            "mycelium_layer_planner/gossip_adapter.py",
        ),
    ),
    ContractSpec(
        "layer-load-proof-v1.json",
        "mycelium.layer_load_proof.v1",
        (
            "runtime_loader.py",
            "runtime_contracts.py",
            "mycelium_router/layer_builder.py",
            "mycelium_router/stage_signatures.py",
        ),
    ),
    ContractSpec(
        "route-qualification-v1.json",
        "mycelium.route_qualification.v1",
        (
            "mycelium_qualification/contracts.py",
            "mycelium_qualification/evidence.py",
            "mycelium_qualification/qualifier.py",
            "mycelium_qualification/authority.py",
        ),
    ),
    ContractSpec(
        "request-gateway-v1.json",
        "mycelium.request_gateway.v1",
        ("mycelium_request_gateway/contracts.py",),
    ),
    ContractSpec(
        "request-gateway-v2.json",
        "mycelium.request_gateway.v2",
        (
            "mycelium_request_gateway/contracts.py",
            "ui/web/src/app/contracts.ts",
        ),
    ),
    ContractSpec(
        "request-event-v1.json",
        "mycelium.request_event.v1",
        ("mycelium_request_gateway/contracts.py",),
    ),
    ContractSpec(
        "request-event-v2.json",
        "mycelium.request_event.v2",
        (
            "mycelium_request_gateway/contracts.py",
            "mycelium_request_gateway/service.py",
            "mycelium_ui_gateway/validation.py",
            "ui/web/src/app/contracts.ts",
        ),
    ),
    ContractSpec(
        "membership-signed-message-v1.json",
        "mycelium.membership.signed_message.v1",
        ("mycelium_membership/contracts.py", "mycelium_qualification/signing.py"),
    ),
    ContractSpec(
        "membership-join-request-v1.json",
        "mycelium.membership.join_request.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-join-acceptance-v1.json",
        "mycelium.membership.join_acceptance.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-resume-request-v1.json",
        "mycelium.membership.resume_request.v1",
        (
            "mycelium_membership/contracts.py",
            "mycelium_node/membership.py",
            "mycelium_seed/coordinator.py",
            "mycelium_seed/http.py",
        ),
    ),
    ContractSpec(
        "membership-resume-acceptance-v1.json",
        "mycelium.membership.resume_acceptance.v1",
        (
            "mycelium_membership/contracts.py",
            "mycelium_node/membership.py",
            "mycelium_seed/coordinator.py",
            "mycelium_seed/state.py",
        ),
    ),
    ContractSpec(
        "membership-capability-report-v1.json",
        "mycelium.membership.capability_report.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-link-probe-report-v1.json",
        "mycelium.membership.link_probe_report.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-heartbeat-v1.json",
        "mycelium.membership.heartbeat.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-lease-renewal-v1.json",
        "mycelium.membership.lease_renewal.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-assignment-offer-v1.json",
        "mycelium.membership.assignment_offer.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-assignment-result-v1.json",
        "mycelium.membership.assignment_result.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-drain-ack-v1.json",
        "mycelium.membership.drain_ack.v1",
        ("mycelium_membership/contracts.py",),
    ),
    ContractSpec(
        "membership-seed-rotation-ack-v1.json",
        "mycelium.membership.seed_rotation_ack.v1",
        (
            "mycelium_membership/contracts.py",
            "mycelium_node/membership.py",
            "mycelium_seed/state.py",
        ),
    ),
    ContractSpec(
        "seed-operator-inventory-v1.json",
        "mycelium.seed_operator_inventory.v1",
        ("mycelium_seed/operator.py", "scripts/manage_seed_membership.py"),
    ),
    ContractSpec(
        "seed-operator-revocation-v1.json",
        "mycelium.seed_operator_revocation.v1",
        ("mycelium_seed/operator.py", "scripts/manage_seed_membership.py"),
    ),
    ContractSpec(
        "seed-key-transition-v1.json",
        "mycelium.seed_key_transition.v1",
        ("mycelium_seed/operator.py", "mycelium_seed/state.py"),
    ),
    ContractSpec(
        "seed-operator-rotation-v1.json",
        "mycelium.seed_operator_rotation.v1",
        (
            "mycelium_seed/operator.py",
            "mycelium_seed/state.py",
            "scripts/manage_seed_membership.py",
        ),
    ),
    ContractSpec(
        "seed-backup-v1.json",
        "mycelium.seed_backup.v1",
        ("mycelium_seed/operator.py", "scripts/manage_seed_membership.py"),
    ),
    ContractSpec(
        "capacity-profile-v1.json",
        "mycelium.capacity_profile.v1",
        (
            "mycelium_capacity_profiles/contracts.py",
            "mycelium_capacity_profiles/compiler.py",
            "mycelium_capacity_profiles/document.py",
        ),
    ),
    ContractSpec(
        "link-state-v1.json",
        "mycelium.link_state.v1",
        ("mycelium_gossip/schema.py",),
    ),
    ContractSpec(
        "product-ui-swarm-v1.json",
        "mycelium.product_ui.swarm.v1",
        ("mycelium_ui_gateway/validation.py", "mycelium_live/route.py"),
    ),
    ContractSpec(
        "live-route-incident-v1.json",
        "mycelium.live_route_incident.v1",
        ("mycelium_live/route.py", "mycelium_live/registry.py"),
    ),
    ContractSpec(
        "performance-budget-v1.json",
        "mycelium.performance_budget.v1",
        ("mycelium_performance_budget.py",),
    ),
    ContractSpec(
        "performance-budget-v2.json",
        "mycelium.performance_budget.v2",
        (
            "mycelium_performance_budget.py",
            "mycelium_layer_planner/workload_intelligence.py",
        ),
    ),
    ContractSpec(
        "performance-budget-v3.json",
        "mycelium.performance_budget.v3",
        ("mycelium_performance_budget.py", "mycelium_m16_runtime.py"),
    ),
    ContractSpec(
        "assignment-artifact-cache-v1.json",
        "mycelium.assignment_artifact_cache.v1",
        ("mycelium_assignment_cache.py",),
    ),
    ContractSpec(
        "assignment-materialization-v1.json",
        "mycelium.assignment_materialization.v1",
        ("mycelium_assignment_cache.py", "layer_assignment.py"),
    ),
    ContractSpec(
        "candidate-promotion-report-v1.json",
        "mycelium.candidate_promotion_report.v1",
        ("mycelium_candidate_promotion.py", "mycelium_live/registry.py"),
    ),
    ContractSpec(
        "m13-placement-projection-v1.json",
        "mycelium.m13_placement_projection.v1",
        (
            "mycelium_layer_planner/public_projection.py",
            "ui/web/src/features/liveRoute/routeStatus.ts",
            "ui/web/src/features/liveRoute/M13PlacementPanel.tsx",
        ),
    ),
    ContractSpec(
        "transport-path-observation-v1.json",
        "mycelium.transport_path_observation.v1",
        (
            "mycelium_topology_evidence.py",
            "mycelium_router/transports/iroh.py",
            "native/iroh_transport/src/sidecar.rs",
        ),
    ),
    ContractSpec(
        "m14-topology-projection-v1.json",
        "mycelium.m14_topology_projection.v1",
        (
            "mycelium_topology_evidence.py",
            "ui/web/src/features/liveRoute/routeStatus.ts",
            "ui/web/src/features/liveRoute/M14TopologyPanel.tsx",
        ),
    ),
    ContractSpec(
        "m15-plan-comparison-v1.json",
        "mycelium.m15_plan_comparison.v1",
        (
            "mycelium_layer_planner/workload_intelligence.py",
            "ui/web/src/features/liveRoute/m15Comparison.ts",
            "ui/web/src/features/liveRoute/M15WorkloadPanel.tsx",
        ),
    ),
    ContractSpec(
        "m16-runtime-status-v1.json",
        "mycelium.m16_runtime_status.v1",
        (
            "mycelium_m16_runtime.py",
            "mycelium_live/router_port.py",
            "ui/web/src/features/liveRoute/m16Runtime.ts",
            "ui/web/src/features/liveRoute/M16RuntimePanel.tsx",
        ),
    ),
    ContractSpec(
        "m23-kv-gate-v1.json",
        "mycelium.m23_heterogeneous_kv_gate.v1",
        (
            "mycelium_m23_kv.py",
            "scripts/run_m23_kv_gate.py",
            "ui/web/src/features/liveRoute/m23Kv.ts",
            "ui/web/src/features/liveRoute/M23KvPanel.tsx",
        ),
    ),
    ContractSpec(
        "product-snapshot-v1.json",
        "mycelium.product_snapshot.v1",
        (
            "mycelium_product_spine/contracts.py",
            "mycelium_product_spine/projector.py",
        ),
    ),
    ContractSpec(
        "product-event-v1.json",
        "mycelium.product_event.v1",
        ("mycelium_product_spine/contracts.py",),
    ),
    ContractSpec(
        "execution-graph-v1.json",
        "mycelium.execution_graph.v1",
        (
            "mycelium_router/contracts.py",
            "mycelium_router/layer_builder.py",
            "mycelium_router/serialization.py",
            "mycelium_router/validation.py",
        ),
    ),
    ContractSpec(
        "path-manifest-v1.json",
        "mycelium.path_manifest.v1",
        (
            "mycelium_router/contracts.py",
            "mycelium_router/serialization.py",
            "mycelium_router/validation.py",
        ),
    ),
    ContractSpec(
        "live-route-status-v1.json",
        "mycelium.live_route_status.v1",
        ("mycelium_live/route.py", "ui/web/src/features/liveRoute/routeStatus.ts"),
    ),
    ContractSpec(
        "deployment-activation-v1.json",
        "mycelium.deployment_activation.v1",
        (
            "mycelium_live/activation.py",
            "mycelium_live/supervisor.py",
            "ui/web/src/features/liveRoute/deploymentActivation.ts",
            "ui/web/src/features/liveRoute/PreparedDeploymentsPanel.tsx",
        ),
    ),
    ContractSpec(
        "deployment-residency-physical-v1.json",
        "mycelium.deployment_residency_physical_gate.v1",
        (
            "docs/superpowers/specs/2026-08-11-mycelium-deployment-residency-control.md",
            "mycelium_live/activation.py",
            "mycelium_live/registry.py",
            "mycelium_live/supervisor.py",
            "ui/web/src/features/liveRoute/deploymentActivation.ts",
            "ui/web/src/features/models/ModelCatalogControlPanel.tsx",
        ),
    ),
    ContractSpec(
        "governance-readiness-v1.json",
        "mycelium.governance_readiness.v1",
        (
            "mycelium_governance.py",
            "mycelium_live/supervisor.py",
            "ui/web/src/features/governance/governanceReadiness.ts",
            "ui/web/src/features/governance/GovernanceReadinessSource.tsx",
        ),
    ),
    ContractSpec(
        "evidence-projection-v1.json",
        "mycelium.evidence_projection.v1",
        (
            "docs/superpowers/specs/2026-08-11-mycelium-a1-live-evidence-separation.md",
            "mycelium_evidence.py",
            "mycelium_live/supervisor.py",
            "ui/web/src/features/evidence/evidenceProjection.ts",
            "ui/web/src/features/evidence/EvidenceProvenanceSource.tsx",
        ),
    ),
    ContractSpec(
        "evidence-history-v1.json",
        "mycelium.evidence_history.v1",
        (
            "docs/superpowers/specs/2026-08-11-mycelium-a1-live-evidence-separation.md",
            "mycelium_evidence.py",
            "mycelium_live/supervisor.py",
            "ui/web/src/features/evidence/evidenceProjection.ts",
            "ui/web/src/features/evidence/EvidenceProvenanceSource.tsx",
        ),
    ),
    ContractSpec(
        "router-wire-v1.json",
        "mycelium.router_wire.v1",
        ("mycelium_router/wire.py", "scripts/generate_router_wire_golden.py"),
    ),
    ContractSpec(
        "layer-replan-simulation-report-v1.json",
        "mycelium.layer_replan_simulation_report.v1",
        (
            "mycelium_layer_planner/replan_simulator.py",
            "scenarios/product-v1-replanning.json",
            "scenarios/product-v1-replicated.json",
        ),
    ),
    ContractSpec(
        "product-ui-bootstrap-v1.json",
        "mycelium.product_ui.bootstrap.v1",
        (
            "mycelium_ui_gateway/app.py",
            "ui/contracts/product/product-ui-bootstrap-v1.schema.json",
            "ui/web/src/app/contracts.ts",
        ),
    ),
    ContractSpec(
        "observatory-snapshot-v1.json",
        "mycelium.observatory.snapshot.v1",
        ("mycelium_gateway/semantic.py",),
    ),
    ContractSpec(
        "observatory-event-v1.json",
        "mycelium.observatory.event.v1",
        ("mycelium_gateway/semantic.py",),
    ),
)

SPECS_BY_FIXTURE = {spec.fixture_name: spec for spec in CONTRACT_SPECS}
EXPECTED_FIXTURE_NAMES = frozenset(SPECS_BY_FIXTURE)
EXPECTED_PROTOCOLS = frozenset(spec.protocol for spec in CONTRACT_SPECS)

if len(SPECS_BY_FIXTURE) != len(CONTRACT_SPECS):
    raise RuntimeError("contract registry contains duplicate fixture names")
if len(EXPECTED_PROTOCOLS) != len(CONTRACT_SPECS):
    raise RuntimeError("contract registry contains duplicate protocol owners")
